### PR TITLE
Added scaling cooldown variables.

### PR DESCRIPTION
**Pull request by Jon-Berg**
## what

Added scaling cooldown variables.

## why

Need to control autoscaling cooldown times to handle usage spikes.

## references

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_policy#target_tracking_scaling_policy_configuration

### CODE REVIEW

**Comment by hans-d** [comment]
@Jon-Berg Hi, can you update the pr so that it passes the tests? otherwise, it is likely to be closed due to staleness.

**Comment by hans-d** [comment]
```
README.md is outdated. Please run the following commands locally and push the file:
  make init
  make readme
```

**Review by hans-d — APPROVED** [review]

**Comment by hans-d** [comment]
there seems to be some issue with the readme generation :-( as some bits seems to be flipping around. Letrs try if we can get lucky - as currently the merging is blocked because of that. WIll raise the readme issue internally.

**Comment by hans-d** [comment]
terratest fix in #55

**Comment by hans-d** [comment]
The build harness that's being used is now updated to fix the flipping readme issues.

**Comment by hans-d** [comment]
@Jon-Berg can you update the readme once more?

**Comment by joe-niland** [comment]
@Jon-Berg would you mind running `terraform fmt` also?

**Review by hans-d — APPROVED** [review]

**Comment by hans-d** [comment]
@Jon-Berg  🎉  Thanks for the ride !

**Comment by hans-d** [comment]
Looking into getting this released (seems also something 🐌 )

**Pull request merged**
