### PR TITLE
[AUTOMATED] Update Version Pinning for Terraform to support 0.13

### PR DESCRIPTION
**Pull request by Gowiem**
## What

* Update Version Pinning for Terraform to support 0.13
* Fix example and Terratest
* Add Go modules for Terratest

## Why

* This is a relatively minor update that the CloudPosse module already likely supports
* This allows module consumers to not individually update our Terraform module to support Terraform 0.13
* Fix example and Terratest: deploy a DynamoDB table to connect the autoscaler to (otherwise, AWS throws errors)
* Add Go modules for Terratest: use Go modules to pin versions

### CODE REVIEW

**Comment by Gowiem** [comment]
Getting the below error. Will need to investigate and fix. 

```
Error: Error putting IAM role policy eg-test-dynamodb-autoscaler-autoscaler-dynamodb: MalformedPolicyDocument: Resource  must be in ARN format or "*".
	status code: 400, request id: 63ef2589-2098-4777-8c6b-33139dbeffa6

  on ../../main.tf line 52, in resource "aws_iam_role_policy" "autoscaler":
  52: resource "aws_iam_role_policy" "autoscaler" {



Error: Error creating application autoscaling target: ValidationException: Unsupported service namespace, resource type or scalable dimension

  on ../../main.tf line 82, in resource "aws_appautoscaling_target" "read_target":
  82: resource "aws_appautoscaling_target" "read_target" {



Error: Error creating application autoscaling target: ValidationException: Unsupported service namespace, resource type or scalable dimension

  on ../../main.tf line 140, in resource "aws_appautoscaling_target" "write_target":
 140: resource "aws_appautoscaling_target" "write_target" {
```

**Comment by aknysh** [comment]
> Getting the below error. Will need to investigate and fix.
> 
> ```
> Error: Error putting IAM role policy eg-test-dynamodb-autoscaler-autoscaler-dynamodb: MalformedPolicyDocument: Resource  must be in ARN format or "*".
> 	status code: 400, request id: 63ef2589-2098-4777-8c6b-33139dbeffa6
> 
>   on ../../main.tf line 52, in resource "aws_iam_role_policy" "autoscaler":
>   52: resource "aws_iam_role_policy" "autoscaler" {
> 
> 
> 
> Error: Error creating application autoscaling target: ValidationException: Unsupported service namespace, resource type or scalable dimension
> 
>   on ../../main.tf line 82, in resource "aws_appautoscaling_target" "read_target":
>   82: resource "aws_appautoscaling_target" "read_target" {
> 
> 
> 
> Error: Error creating application autoscaling target: ValidationException: Unsupported service namespace, resource type or scalable dimension
> 
>   on ../../main.tf line 140, in resource "aws_appautoscaling_target" "write_target":
>  140: resource "aws_appautoscaling_target" "write_target" {
> ```

I'm looking into that

**Pull request merged**
