### PR TITLE
Terraform 0.14 upgrade

### PR DESCRIPTION
**Pull request by maximmi**
## what
- Upgrade to support Terraform 0.14 and bring up to current Cloud Posse standard

## why
- Support Terraform 0.14

### CODE REVIEW

**Review by mcalhoun — CHANGES_REQUESTED** [review]
When you use expressions in an if conditional, you may omit the expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression. For more information about if conditionals, see [Workflow syntax for GitHub Actions.](https://docs.github.com/en/free-pro-team@latest/articles/workflow-syntax-for-github-actions/#jobsjob_idif)

**Review by mcalhoun — APPROVED** [review]
LGTM!

**Review by osterman — APPROVED** [review]

**Pull request merged**
